<a href="https://colab.research.google.com/github/Abdul-Lahad/PyTorch-Tutorial/blob/main/Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Tutorial 03: Gradient Calculation With Autograd
#### 1. Introduction to Autograd
- PyTorch's `autograd` package automates gradient computation, essential for model optimization.
- Use the `requires_grad=True` argument to enable gradient tracking for tensors.

#### 2. Computational Graph and Forward Pass
- PyTorch builds a computational graph when operations are performed on tensors with `requires_grad=True`.
- The graph is used for gradient computation via backpropagation.

#### 3. Gradient Calculation
- Forward pass computes outputs, and backpropagation calculates gradients using gradient functions (e.g., `AddBackward`, `MulBackward`).
- Use the `.backward()` function to compute gradients stored in the `.grad` attribute.

#### 4. Scalar and Non-Scalar Outputs
- For scalar outputs, `.backward()` works directly.
- For non-scalar outputs, provide a gradient vector of the same size to `.backward()`.

#### 5. Preventing Gradient Tracking
- To exclude operations from gradient tracking:
  1. Set `requires_grad=False`.
  2. Use `.detach()` to create a tensor without gradient tracking.
  3. Use `torch.no_grad()` within a context manager.

#### 6. Gradient Accumulation
- Gradients accumulate in the `.grad` attribute during multiple `.backward()` calls.
- Clear gradients using `.grad.zero_()` before the next iteration.

#### 7. PyTorch Optimizer Integration
- PyTorch optimizers (e.g., `torch.optim.SGD`) manage gradient updates.
- Use `.zero_grad()` to reset gradients before new iterations.

#### 8. Key Takeaways
- Use `requires_grad=True` for tensors requiring gradient computation.
- Clear gradients before subsequent iterations in training loops.
- Understand how to prevent gradient tracking when necessary.

#### 9. Conclusion
- Encouragement to explore more about `autograd` for effective model optimization.
- Subscribe to the channel for more tutorials!


In [1]:
import torch

In [18]:
x = torch.randn(5,requires_grad=True)
print(x)

y = x + 4.3
print(y)

z = y*2
print(z)

print(f'z = {z}')
print(f'x = {x}')
z.backward(torch.ones_like(x))
print(x.grad)


tensor([-0.5273,  0.3019, -1.2014,  2.4427, -0.1585], requires_grad=True)
tensor([3.7727, 4.6019, 3.0986, 6.7427, 4.1415], grad_fn=<AddBackward0>)
tensor([ 7.5454,  9.2039,  6.1972, 13.4855,  8.2830], grad_fn=<MulBackward0>)
z = tensor([ 7.5454,  9.2039,  6.1972, 13.4855,  8.2830], grad_fn=<MulBackward0>)
x = tensor([-0.5273,  0.3019, -1.2014,  2.4427, -0.1585], requires_grad=True)
tensor([2., 2., 2., 2., 2.])


In [21]:
weights = torch.randn(5,requires_grad=True)

for epochs in range(3):
    model_output = (weights * 6).sum()

    model_output.backward()

    print(weights.grad)

    # after each iteration we must empty the gradient of the vactor
    weights.grad.zero_()

tensor([6., 6., 6., 6., 6.])
tensor([6., 6., 6., 6., 6.])
tensor([6., 6., 6., 6., 6.])
