<a href="https://colab.research.google.com/github/Abdul-Lahad/PyTorch-Tutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor** **Basics**
* By default the tensor have the data type Float32.
* IF you want to change the data type then after specify the dimension of the tensor use property dtype.
  * torch.double
  * torch.float16 e.t.c











In [2]:
import torch
import numpy as np


In [14]:
my_tensor = torch.empty(3) # this will create the 1D tensor
my_tensor = torch.rand(2,2) # this will create the random number 2D tensor
my_tensor = torch.zeros(2,2) # this will create the zero 2D tensor
my_tensor = torch.ones(2,2) # this will create the one 2D tensor
my_tensor = torch.eye(2,2) # this will create the identity 2D tensor

my_tensor_1 = torch.tensor([[5,2,3],[4,4,2]]) # this will create the custom 2D tensor
my_tensor_2 = torch.tensor([[1,7,3],[4,7,9]]) # this will create the custom 2D tensor

z = my_tensor_1 + my_tensor_2 # this will add the two tensor
z = my_tensor_1 - my_tensor_2 # this will subtract the two tensor
z = my_tensor_1 * my_tensor_2 # this will multiply the two tensor
z = my_tensor_1 / my_tensor_2 # this will divide the two tensor

z = torch.add(my_tensor_1,my_tensor_2) # this will add the two tensor
z = torch.sub(my_tensor_1,my_tensor_2) # this will subtract the two tensor
z = torch.mul(my_tensor_1,my_tensor_2) # this will multiply the two tensor
z = torch.div(my_tensor_1,my_tensor_2) # this will divide the two tensor

my_tensor_1.add_(my_tensor_2) # this will add the two tensor and stors the anser in the first tensor

my_tensor_1 = torch.tensor([[5,2,3],
                            [4,4,2]]) # this will create the custom 2D tensor

my_tensor_2 = torch.tensor([[1,7,3],
                            [4,7,9],
                            [4,7,9]]) # this will create the custom 2D tensor


z = torch.matmul(my_tensor_1,my_tensor_2) # this will multiply the two tensor but it is the cross product.


tensor([[25, 70, 60],
        [28, 70, 66]])


## Slicing and Reshaping Tensor
* For Reshaping the **Tensor**, In pytorch have tow methods.
    * reshap()
    * view()

In [20]:
x = my_tensor_2[:,1] # it give all the rows and index 1 column
x = my_tensor_2[2,2] # it will give the single element but its dataType is tensor
x = my_tensor_2[2,2].item() # it will give the single element but its dataType is int

### Reshap Tensor ###
x = my_tensor_2.view(1,-1) # this 2D Tensor,1 denots 1 Row and -1 denots Possible column this can be done vice versa

print(x.size())

torch.Size([1, 9])


## Conversion of Tensor and Numpy Array
* Tensor to Numpy || Array numpy()
* Numpy to Tensor || torch.from_numpy(array)


In [3]:
my_tensor_1 = torch.ones(2,2) # this will create the custom 2D tensor
print(my_tensor_1)

a = my_tensor_1.numpy()
print(a)
print(type(a))
b = torch.from_numpy(a)

a += 1;
print(a)

print(b)
print(type(b))


tensor([[1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
[[2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.]])
<class 'torch.Tensor'>
